version: '3'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_container
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data_container:/data/mongodb    
    webserver:
      image: webprogrammierung:latest
      container_name: webserver_container
      #restart: always
      build:
        dockerfile: Dockerfile
        context: .
      ports:
        - "9090:9090"

volumes:
    mongodb_data_container:

